<a href="https://colab.research.google.com/github/ajayshgithub/Project-1/blob/main/BHPusingKerasAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load Tensorflow


In [ ]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [ ]:
import tensorflow as tf
tf.__version__

'2.11.0'

Collect Data

In [ ]:
#Load Boston Housing Dataset
(train_x, train_y),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

#No need to change float notation with Keras API as it is automatically taken care of

57026/57026 [==============================] - 0s 0us/step


Normalize input features

In [ ]:
#Import MinMaxScaler from scikit learn
from sklearn.preprocessing import MinMaxScaler

In [ ]:
#Normalize the input features
transformer = MinMaxScaler()
train_x = transformer.fit_transform(train_x)

Building the Graph in Keras

In [ ]:
#Initialize Sequential Graph(model)
model = tf.keras.Sequential()

#Add Dense layer for prediction- keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, input_shape=(13,)))
#here 1 repesents only 1 equation  y=wx+b

#Compile the model- add loss and gradient descent optimizer
model.compile(optimizer='sgd' , loss='mse')

Execute the Graph

In [ ]:
#Train the model
model.fit(train_x, train_y, epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 3ms/step - loss: 327.8958
Epoch 2/100
16/16 [==============================] - 0s 3ms/step - loss: 126.4548
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 100.6808
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 90.4137
Epoch 5/100
16/16 [==============================] - 0s 3ms/step - loss: 83.3185
Epoch 6/100
16/16 [==============================] - 0s 10ms/step - loss: 77.5225
Epoch 7/100
16/16 [==============================] - 0s 13ms/step - loss: 72.6756
Epoch 8/100
16/16 [==============================] - 0s 11ms/step - loss: 68.8299
Epoch 9/100
16/16 [==============================] - 0s 8ms/step - loss: 65.5556
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 62.8214
Epoch 11/100
16/16 [==============================] - 0s 3ms/step - loss: 60.5044
Epoch 12/100
16/16 [==============================] - 0s 3ms/step - loss: 58.4380
Epoch 13/100
16/16 

In [ ]:
#Check model weights
model.get_weights()

[array([[ -1.6180788 ],
        [  4.2028675 ],
        [ -1.7650368 ],
        [  4.115849  ],
        [ -0.73137075],
        [ 18.00707   ],
        [  1.7301326 ],
        [ -0.8159915 ],
        [  1.6140555 ],
        [ -2.4528325 ],
        [ -5.491108  ],
        [  8.042758  ],
        [-11.797028  ]], dtype=float32), array([12.548626], dtype=float32)]

Save the Model

In [ ]:
#Saving the model
model.save('boston_housing_lr.h5')


In [ ]:
!ls -l

total 24
-rw-r--r-- 1 root root 17600 Mar 26 07:17 boston_housing_lr.h5
drwxr-xr-x 1 root root  4096 Mar 23 18:57 sample_data


Model Prediction

In [ ]:
import tensorflow as tf

In [ ]:
#Load the saved model, you will usually do it in a different program
model = tf.keras.models.load_model('boston_housing_lr.h5')

In [ ]:
#Prepare data on which you want to predict , here we need 13 input features
input_data = [1.23, 0, 8.14, 0, 0.54, 6.14, 91.7, 3.98, 4, 307, 21, 396.9, 18.72]

In [ ]:
#Convert the data to numpy array
import numpy as np
input_data= np.reshape(input_data,(1,13))

#Check the input data shape, it should be(1,13) i.e. one example with 13 features
input_data.shape

(1, 13)

In [ ]:
#Check the data
input_data

array([[  1.23,   0.  ,   8.14,   0.  ,   0.54,   6.14,  91.7 ,   3.98,
          4.  , 307.  ,  21.  , 396.9 ,  18.72]])

In [ ]:
#Normalize the data with MinMaxScaler - WE NEED TO DO SAME DATA PRE-PROCESSING as done during training
input_data = transformer.transform(input_data)

#Print normalize input_data
input_data

array([[0.01375387, 0.        , 0.28152493, 0.        , 0.31893004,
        0.49415597, 0.91452111, 0.25920032, 0.13043478, 0.22900763,
        0.89361702, 1.        , 0.46881898]])

In [ ]:
#Prediction on input_data
model.predict(input_data)

1/1 [==============================] - 0s 98ms/step


array([[19.319204]], dtype=float32)